=== Akashdeep-Kallon/M0373-Llenguatge-de-Marques-i-sistemes-de-gestio-d-informacio/XML y DTD/PR3/contactes.dtd
<!ELEMENT contactes (contacte+)>

<!ELEMENT contacte (nom, edat, cognoms, telefons, direccio, email)>
<!ATTLIST contacte familiar (si|no) #REQUIRED>

<!ELEMENT nom (#PCDATA)>
<!ELEMENT edat (#PCDATA)>

<!ELEMENT cognoms (congnom+)>
<!ELEMENT congnom (#PCDATA)>
<!ATTLIST congnom order CDATA #REQUIRED>

<!ELEMENT telefons (telefon+)>
<!ELEMENT telefon (prefix, numeroTelefon, tipus)>

<!ELEMENT prefix (#PCDATA)>
<!ELEMENT numeroTelefon (#PCDATA)>
<!ELEMENT tipus (#PCDATA)>

<!ELEMENT direccio (carrer, numeroDireccio, codiPostal, ciutat)>
<!ATTLIST direccio principal (si|no) #REQUIRED>

<!ELEMENT carrer (#PCDATA)>
<!ELEMENT numeroDireccio (#PCDATA)>
<!ELEMENT codiPostal (#PCDATA)>
<!ELEMENT ciutat (#PCDATA)>

<!ELEMENT email (#PCDATA)>

=== Akashdeep-Kallon/M0373-Llenguatge-de-Marques-i-sistemes-de-gestio-d-informacio/RA1/Pr3/contactes.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE contactes SYSTEM "contactes.dtd">

<contactes>
    <contacte familiar="si">
        <nom>Samuel</nom>
        <edat>36</edat>
        <cognoms>
            <congnom order="1">DeLoque</congnom>
            <congnom order="2">Batuecas</congnom>
        </cognoms>

        <telefons>
            <telefon>
                <prefix>+34</prefix>
                <numeroTelefon>943576808</numeroTelefon>
                <tipus>fix</tipus>
            </telefon>
            <telefon>
                <prefix>+34</prefix>
                <numeroTelefon>612341674</numeroTelefon>
                <tipus>mobil</tipus>
            </telefon>
        </telefons>

        <direccio principal="si">
            <carrer>c/ Muntaner</carrer>
            <numeroDireccio>177</numeroDireccio>
            <codiPostal>08006</codiPostal>
            <ciutat>Barcelona</ciutat>
        </direccio>
        <email>vegetta777@gmail.com</email>
    </contacte>

    <contacte familiar="no">
        <nom>Guillermo</nom>
        <edat>32</edat>
        <cognoms>
            <congnom order="1">Díaz</congnom>
            <congnom order="2">Ibáñez</congnom>
        </cognoms>

        <telefons>
            <telefon>
                <prefix>+34</prefix>
                <numeroTelefon>936547889</numeroTelefon>
                <tipus>fix</tipus>
            </telefon>
            <telefon>
                <prefix>+34</prefix>
                <numeroTelefon>612435763</numeroTelefon>
                <tipus>mobil</tipus>
            </telefon>
        </telefons>

        <direccio principal="no">
            <carrer>c/ Muntaner</carrer>
            <numeroDireccio>177</numeroDireccio>
            <codiPostal>08006</codiPostal>
            <ciutat>Barcelona</ciutat>
        </direccio>
        <email>WillyRex@gmail.com</email>
    </contacte>
</contactes>
