=== Akashdeep-Kallon/M0373-Llenguatge-de-Marques-i-sistemes-de-gestio-d-informacio/RA1/Pr4/equipos.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="equipos">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="equipo" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombreEquipo">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string"></xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="tipoTrabajo">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string"></xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="director">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string"></xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="resultados">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="year" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="exitos">
                                                        <xs:simpleType>
                                                            <xs:restriction base="xs:integer">
                                                                <xs:minInclusive value="0"></xs:minInclusive>
                                                            </xs:restriction>
                                                        </xs:simpleType>
                                                    </xs:element>
                                                    <xs:element name="fracasos">
                                                        <xs:simpleType>
                                                            <xs:restriction base="xs:integer">
                                                                <xs:minInclusive value="0"></xs:minInclusive>
                                                            </xs:restriction>
                                                        </xs:simpleType>
                                                    </xs:element>
                                                </xs:sequence>
                                                <xs:attribute name="valor" use="required">
                                                    <xs:simpleType>
                                                        <xs:restriction base="xs:integer"></xs:restriction>
                                                    </xs:simpleType>
                                                </xs:attribute>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="integrantes">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="integrante" minOccurs="1" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="nombre">
                                                        <xs:simpleType>
                                                            <xs:restriction base="xs:string">
                                                                <xs:minLength value="3"></xs:minLength>
                                                                <xs:maxLength value="20"></xs:maxLength>
                                                            </xs:restriction>
                                                        </xs:simpleType>
                                                    </xs:element>
                                                    <xs:element name="apellido">
                                                        <xs:simpleType>
                                                            <xs:restriction base="xs:string">
                                                                <xs:minLength value="3"></xs:minLength>
                                                                <xs:maxLength value="20"></xs:maxLength>
                                                            </xs:restriction>
                                                        </xs:simpleType>
                                                    </xs:element>
                                                    <xs:element name="cargo">
                                                        <xs:simpleType>
                                                            <xs:restriction base="xs:string">
                                                                <xs:minLength value="3"></xs:minLength>
                                                                <xs:maxLength value="20"></xs:maxLength>
                                                            </xs:restriction>
                                                        </xs:simpleType>
                                                    </xs:element>
                                                    <xs:element name="fechaNacimiento">
                                                        <xs:simpleType>
                                                            <xs:restriction base="xs:date">
                                                                <xs:maxExclusive value="2000-01-01"></xs:maxExclusive>
                                                            </xs:restriction>
                                                        </xs:simpleType>
                                                    </xs:element>
                                                    <xs:element name="imagenRuta">
                                                        <xs:simpleType>
                                                            <xs:restriction base="xs:string"></xs:restriction>
                                                        </xs:simpleType>
                                                    </xs:element>
                                                    <xs:element name="ultimaHoraParticipacion">
                                                        <xs:simpleType>
                                                            <xs:restriction base="xs:time"></xs:restriction>
                                                        </xs:simpleType>
                                                    </xs:element>
                                                    <xs:element name="ultimaFechaParticipacion">
                                                        <xs:simpleType>
                                                            <xs:restriction base="xs:date"></xs:restriction>
                                                        </xs:simpleType>
                                                    </xs:element>
                                                    <xs:element name="estadisticas">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="programasRealizados">
                                                                    <xs:simpleType>
                                                                        <xs:restriction base="xs:integer">
                                                                            <xs:minInclusive value="0"></xs:minInclusive>
                                                                        </xs:restriction>
                                                                    </xs:simpleType>
                                                                </xs:element>
                                                                <xs:element name="bugsResueltos">
                                                                    <xs:simpleType>
                                                                        <xs:restriction base="xs:integer">
                                                                            <xs:minInclusive value="0"></xs:minInclusive>
                                                                        </xs:restriction>
                                                                    </xs:simpleType>
                                                                </xs:element>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
        <!-- El ejercicio 3 pide que algunos elementos sean únicos, pero como el documento de teoria no aparece nada de como 
         hacer un elemento como único lo he buscado y lo he hecho así. Como no lo haz expliacado entiendo que no lo pides, pero
         por si acaso lo he hecho igualmente. -->
        <xs:unique name="nombreUnico">
            <xs:selector xpath="equipo"/>
            <xs:field xpath="nombreEquipo"/>
        </xs:unique>

        <xs:unique name="tipoUnico">
            <xs:selector xpath="equipo"/>
            <xs:field xpath="tipoTrabajo"/>
        </xs:unique>

        <xs:unique name="directorUnico">
            <xs:selector xpath="equipo"/>
            <xs:field xpath="director"/>
        </xs:unique>
    </xs:element>
</xs:schema>

=== Akashdeep-Kallon/M0373-Llenguatge-de-Marques-i-sistemes-de-gestio-d-informacio/RA1/Pr4/equipos.xml
<?xml version="1.0" encoding="UTF-8"?>
<equipos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="equipos.xsd">
    <equipo>
        <nombreEquipo>CodeMasters</nombreEquipo>
        <tipoTrabajo>desarrollo de software</tipoTrabajo>
        <director>Laura Sánchez</director>

        <resultados>
            <year valor="2022">
                <exitos>12</exitos>
                <fracasos>3</fracasos>
            </year>
            <year valor="2023">
                <exitos>15</exitos>
                <fracasos>2</fracasos>
            </year>
        </resultados>

        <integrantes>
            <integrante>
                <nombre>Daniel</nombre>
                <apellido>Martínez</apellido>
                <cargo>Backend Developer</cargo>
                <fechaNacimiento>1995-04-12</fechaNacimiento>
                <imagenRuta>/imagenes/equipo/daniel.png</imagenRuta>
                <ultimaHoraParticipacion>09:30:00</ultimaHoraParticipacion>
                <ultimaFechaParticipacion>2024-11-15</ultimaFechaParticipacion>

                <estadisticas>
                    <programasRealizados>34</programasRealizados>
                    <bugsResueltos>120</bugsResueltos>
                </estadisticas>
            </integrante>

            <integrante>
                <nombre>Elena</nombre>
                <apellido>Ruiz</apellido>
                <cargo>Frontend Developer</cargo>
                <fechaNacimiento>1998-09-02</fechaNacimiento>
                <imagenRuta>/imagenes/equipo/elena.png</imagenRuta>
                <ultimaHoraParticipacion>10:15:00</ultimaHoraParticipacion>
                <ultimaFechaParticipacion>2024-11-15</ultimaFechaParticipacion>

                <estadisticas>
                    <programasRealizados>27</programasRealizados>
                    <bugsResueltos>89</bugsResueltos>
                </estadisticas>
            </integrante>
        </integrantes>
    </equipo>
</equipos>
