=== Akashdeep-Kallon/M0373-Llenguatge-de-Marques-i-sistemes-de-gestio-d-informacio/RA1/Pr4/gruposMusica.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="grupos">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="grupo" minOccurs="2" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre" minOccurs="1" maxOccurs="1">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:minLength value="5"></xs:minLength>
                                        <xs:maxLength value="25"></xs:maxLength>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="genero" minOccurs="0" maxOccurs="unbounded">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="rap"></xs:enumeration>
                                        <xs:enumeration value="pop"></xs:enumeration>
                                        <xs:enumeration value="folk"></xs:enumeration>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="contactos">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="email" minOccurs="0" maxOccurs="unbounded">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string"></xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="facebook" minOccurs="0" maxOccurs="1">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string"></xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="instagram" minOccurs="0" maxOccurs="1">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string"></xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="twitter" minOccurs="0" maxOccurs="1">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string"></xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="WebOficial" minOccurs="0">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:minLength value="20"></xs:minLength>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="integrantes">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="integrante" minOccurs="1" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="edad">
                                                        <xs:simpleType>
                                                            <xs:restriction base="xs:integer">
                                                                <xs:minInclusive value="5"></xs:minInclusive>
                                                                <xs:maxInclusive value="150"></xs:maxInclusive>
                                                            </xs:restriction>
                                                        </xs:simpleType>
                                                    </xs:element>
                                                    <xs:element name="nombre">
                                                        <xs:simpleType>
                                                            <xs:restriction base="xs:string">
                                                                <xs:minLength value="2"></xs:minLength>
                                                                <xs:maxLength value="30"></xs:maxLength>
                                                            </xs:restriction>
                                                        </xs:simpleType>
                                                    </xs:element>
                                                </xs:sequence>
                                                <xs:attribute name="funcion" use="required">
                                                    <xs:simpleType>
                                                        <xs:restriction base="xs:string">
                                                            <xs:enumeration value="vocalista"></xs:enumeration>
                                                            <xs:enumeration value="bajo"></xs:enumeration>
                                                            <xs:enumeration value="bateria"></xs:enumeration>
                                                        </xs:restriction>
                                                    </xs:simpleType>
                                                </xs:attribute>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
        <!-- El ejercicio 2 pide que los elementos nombre y edad del integrante sean únicos, pero como el documento 
         de teoria no aparece nada de como hacer un elemento como único lo he buscado y lo he hecho así. 
         Como no lo haz expliacado entiendo que no lo pides, pero por si acaso lo he hecho igualmente. -->
        <xs:unique name="nombreIntegranteUnico">
            <xs:selector xpath="grupo/integrantes/integrante"/>
            <xs:field xpath="nombre"/>
        </xs:unique>

        <xs:unique name="edadUnica">
            <xs:selector xpath="grupo/integrantes/integrante"/>
            <xs:field xpath="edad"/>
        </xs:unique>
    </xs:element>
</xs:schema>

=== Akashdeep-Kallon/M0373-Llenguatge-de-Marques-i-sistemes-de-gestio-d-informacio/RA1/Pr4/gruposMusica.xml
<?xml version="1.0" encoding="UTF-8"?>
<grupos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="gruposMusica.xsd">
    <grupo>
        <nombre>Ritmo Urbano</nombre>
        <genero>rap</genero>
        <contactos>
            <email>contacto@ritmourbano.com</email>
            <facebook>facebook.com/ritmourbano</facebook>
            <instagram>instagram.com/ritmourbano</instagram>
        </contactos>
        <WebOficial>https://www.ritmourbanooficial.com</WebOficial>
        <integrantes>
            <integrante funcion="vocalista">
                <edad>28</edad>
                <nombre>Marco Díaz</nombre>
            </integrante>
            <integrante funcion="bajo">
                <edad>34</edad>
                <nombre>Javier Torres</nombre>
            </integrante>
        </integrantes>
    </grupo>
    <grupo>
        <nombre>Melodía Viva</nombre>
        <genero>pop</genero>
        <genero>folk</genero>
        <contactos>
            <email>info@melodiaviva.es</email>
            <twitter>twitter.com/melodiaviva</twitter>
        </contactos>
        <WebOficial>https://www.melodiaviva-musica.es</WebOficial>
        <integrantes>
            <integrante funcion="bateria">
                <edad>25</edad>
                <nombre>Lucía Pérez</nombre>
            </integrante>
            <integrante funcion="vocalista">
                <edad>31</edad>
                <nombre>Daniel Romero</nombre>
            </integrante>
        </integrantes>
    </grupo>
</grupos>
