=== Akashdeep-Kallon/M0373-Llenguatge-de-Marques-i-sistemes-de-gestio-d-informacio/RA1/Pr4/libros.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <xs:element name="libros">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="libro" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>

                            <xs:element name="titulo">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:maxLength value="29"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>

                            <xs:element name="escritores">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="autor" type="xs:string" maxOccurs="unbounded"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>

                            <xs:element name="ediciones">
                                <xs:complexType>
                                    <xs:attribute name="numero" type="xs:integer" use="required"/>
                                </xs:complexType>
                            </xs:element>

                            <xs:element name="publicacion" type="xs:date"/>

                            <xs:element name="genero" maxOccurs="unbounded">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="fantástico"/>
                                        <xs:enumeration value="histórico"/>
                                        <xs:enumeration value="terror"/>
                                        <xs:enumeration value="thriller"/>
                                        <xs:enumeration value="humor"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>

                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== Akashdeep-Kallon/M0373-Llenguatge-de-Marques-i-sistemes-de-gestio-d-informacio/RA1/Pr4/libros.xml
<?xml version="1.0" encoding="UTF-8"?>
<libros xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="libros.xsd">
    <libro>
        <titulo>Sombras del Viento</titulo>
        <escritores>
            <autor>Laura Méndez</autor>
            <autor>Carlos Ruiz</autor>
        </escritores>
        <ediciones numero="3" />
        <publicacion>2018-05-12</publicacion>
        <genero>fantástico</genero>
        <genero>thriller</genero>
    </libro>
</libros>
